### ISSUE TITLE
[FEATURE] Create API to change the settings from projects monitor

### ISSUE THREAD

**Issue by guibranco** [guibranco/gstraccini-bot-api#6]
### Description

Create a REST API to change the bot settings from the [Projects Monitor](https://github.com/guibranco/projects-monitor) project.

### Tech notes

- [ ] guibranco/gstraccini-bot-api#5
- [ ] guibranco/gstraccini-bot-api#4
- [ ] guibranco/gstraccini-bot-api#3
- [x] guibranco/gstraccini-bot-service#545
